# Generated by Django 4.2 on 2023-06-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
