# Generated by Django 4.2 on 2023-06-11 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_archivedorder_order_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='archivedorder',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='archivedorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.product'),
        ),
        migrations.AddField(
            model_name='archivedorder',
            name='status',
            field=models.CharField(max_length=235, null=True),
        ),
    ]
