# Generated by Django 4.2 on 2023-07-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_color_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='colorName',
            new_name='Name',
        ),
    ]
