# Generated by Django 4.2 on 2023-07-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_colorname_color_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='color',
            name='code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
