# Generated by Django 4.2 on 2023-07-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_fabric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='customer',
            name='barangay',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='Pansamantala', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='Pansamantala', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='mi',
            field=models.CharField(default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='municipality',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='province',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='region',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
