# Generated by Django 4.2 on 2023-07-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customer_username_alter_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='dflt.jpg', null=True, upload_to=''),
        ),
    ]
